### ISSUE TITLE
Mascot Capsule 3D support

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#240]
Does the emulator now support Mascot Capsule 3D? Some games like Metal Gear Acid 3d and Devil May Cry 3D are working, but with graphics problems.

**Comment by oatmeal01** [comment]
I can open blades and magic 3d (1.2mb) v1.0.9 now. The only problem is graphical bug.

**Comment by nikita36078** [comment]
No, I just added stubs to get rid of crashes, Mascot Capsule still isn't supported.

**Comment by RyukenT** [comment]
![screenshot_20180324-025829](https://user-images.githubusercontent.com/37715742/37854068-456322a4-2ee1-11e8-9ed1-3a566cfe9509.png)
![screenshot_20180324-025850](https://user-images.githubusercontent.com/37715742/37854069-4818c6c0-2ee1-11e8-819e-f26baa1a0b55.png)

**Comment by RyukenT** [comment]
Need for speed hot pursuit bonus edition(K800i)240x320 1.6mb does open but runs like the images seen  this SS

**Comment by Witiko** [comment]
@nikita36078 As a tech enthusiast back in the day of J2ME, I have a vague understanding that Mascot Capsule 3D is difficult to implement, simply because I never came across an emulator that would support it. However, the hardware won't stay around forever, so we need a free implementation sooner or later.

As a donor and a potential contributor of the J2ME-Loader project, I would like to know what you think is the main obstacle to implementing Mascot Capsule 3D. We know the Mascot Capsule 3D API, so is this just a question of implementing the API, or are there some proprietary file formats that would need reverse-engineering?

**Comment by nikita36078** [comment]
There's a two main problems:
1) Mascot Capsule uses two proprietary formats - mbac (for 3D models) and mtra (for animations). They were partially [decrypted](https://minexew.github.io/2018/12/29/mascotcapsule.html), but there's still some gaps.
2) The documentation is quite minimalistic and doesn't contain all needed information. We can reverse engineer Sony Ericsson SDK, Docomo SDK and a few development tools to get more info about engine.

Thanks to SE SDK we don't need a real hardware, it fully supports MC.
I've started to write a MC implementation (based on @minexew work) and @woesss has managed to get some games working in his [fork](https://github.com/woesss/J2ME-Loader/tree/MC3DE). With a lot of problems, but still a great news.

**Comment by Witiko** [comment]
That's great news indeed, thank you for the detailed write-up. Let me see if I can help with some of the outstanding issues.

**Comment by minexew** [comment]
@nikita36078 If it is of any use, here is my unfinished code: https://github.com/minexew/freej2me-private/commits/micro3d
I never started doing rendering in-emulator, instead it dumps a command list to a file which can be then rendered using a python script. There's a sample video too, showing some rendering from Galaxy on Fire.

**Comment by nikita36078** [comment]
@minexew Thanks for sharing, the code looks interesting, especially the command list part.
