### ISSUE TITLE
Menu button doesn't work properly in wolfenstein rpg

### ISSUE THREAD

**Issue by dyharlan** [nikita36078/J2ME-Loader#27]
Whenever I press the menu button ingame, instead of taking me to the pause menu,  it just turns left. I tried multiple jar files, diff versions, still the same. Tried on these phones:
Samsung Galaxy S II I9100
CM13 Android 6.0.1
Loader 1.2.3

And

Lenovo a536
Stock Android 4.4.4
Loader 1.2.3

Still the same prob

**Comment by nikita36078** [comment]
I moved the emulator menu to the ActionBar(commit 54a3910), so this bug has been fixed since version 1.2.4.

**Comment by dyharlan** [comment]
Nope, menu ingame still wont work

**Comment by nikita36078** [comment]
@dyharlan, does anything happen when you press 3-dot button?

**Comment by dyharlan** [comment]
The issue I have is when I press the pause button to the bottom left of the game, instead of showing the pause menu, it just turns left. This is bad especially for weapons. The app menu isn't the prob

**Comment by nikita36078** [comment]
I think it is can be caused  by the wrong keycodes, I'm planning to add more keycode variants in future versions.

**Comment by RunoFawkes** [comment]
I guess Nikita already understood whats happening, but since I have this game as well I thought I'd add a little more detail to this report. 

Wolfenstein RPG, L is used to pause the game and go to the ingame menu.
Every keymap works correctly in J2ME Loader for this game, except the L button, which seems to turn left.

As additional info, have the full Wolfenstein RPG keymapping:
D and C do nothing.
1 and 3 strafe left and right, respectively.
2 and 8 are the same as Up and Down, they move forward and backward.
4 and 6 are the same as Left and Right, they turn left and right.
9 passes your turn.
7 and * changes to the next weapon and the previous weapon, respectively.
# and R open the map.
0 and L open the menu.

0 does open the menu in J2ME Loader, but L doesn't.

**Comment by AdityaMH** [comment]
Midi Mobile Editor too, normaly "L" is open menu editor. but in J2ME Loader, it's going to turn left.

**Comment by nikita36078** [comment]
This bug is fixed in the last version.
