### ISSUE TITLE
Deep 3D - HUD glitch

### ISSUE THREAD

**Issue by nikita36078** [nikita36078/J2ME-Loader#327]
**Emulator version:**
1.2.9-open

**Game resolution:**
240x320

**Device:**
Lenovo A1000

**Android version:**
5.0

**Description of the issue:**
![39667476-bfbf7eda-50a6-11e8-9812-281fae9068df](https://user-images.githubusercontent.com/3035571/39672392-1d71a34c-5132-11e8-9315-3d3222fc078f.png)

**Comment by Nicat93** [comment]
Yeah, got the same. This is probably my favorite game of all time... aaahhh, whatever, I just want to show off my "setup" :P. 

![screenshot_2018-05-09-23-25-41](https://user-images.githubusercontent.com/8430147/39835193-7512aa00-53e0-11e8-8bba-d43bf29d6f21.png)

**Comment by AdityaMH** [comment]
what game version your playing, @Nicat93?

**Comment by Nicat93** [comment]
It's 1.0.8. But I don't think version has any importance here. If you are interested in Screen Options: 
Resolution: 528x297,
Scale: 100%,
Screen orientation: Landscape,
All checked except for Filter. It tanked the performance so I kept it unchecked but it makes everything "smoother".
For some reason ~1000 vertical/horizontal is the maximum I could go without breaking rendering (probably it is due to game not J2ME's fault), it was too much for my Moto X (2013) anyway.

**Comment by AutoVeron** [comment]
Where did you download that version, @Nicat93? My game has an issue with the   sea background... It turned to whatever color the dominant algae is
![screenshot_2018-05-19-21-50-44](https://user-images.githubusercontent.com/39435716/40274280-5781fe98-5bc2-11e8-88b8-918e36483ff2.jpg)

**Comment by AutoVeron** [comment]
@Nicat93  Downloaded it, but the glitch still persist. Maybe because my phone

**Comment by Nicat93** [comment]
@AutoVeron Oh, that sucks. Have you tried setting resolution to default. Because when I made res too high same color problem happened but nothing was visible except for interface. But in your pic at least models are visible. Guess you found yet another bug :P

**Comment by nikita36078** [comment]
@AutoVeron, what phone do you use? Some 3D games run with glitches on Mali GPUs.

**Comment by AutoVeron** [comment]
@nikita36078 I use Advan G1 Pro (an Indonesian phone) and yes, it is using Mali (T720 MP2).

**Comment by nikita36078** [comment]
Fixed
