### ISSUE TITLE
Snake III not working

### ISSUE THREAD

**Issue by wb9688** [nikita36078/J2ME-Loader#466]
**Emulator version:** 1.4.1

**Game version:** 2.9.1

**Game resolution:** 240x320

**Device:** Moto G5 Plus

**Android version:** 8.1.0

**Description of the issue:** When trying to start a game, it shows the loading screen and then I get the crash reporter.

**Comment by Bakugan77** [comment]
![screenshot_20190218-202648](https://user-images.githubusercontent.com/47291055/52959810-1c523400-338f-11e9-9c83-4ae0d19dfa57.png)
Works fine on me..Nokia 2700 classic.From dedomil.net

**Comment by Bakugan77** [comment]
I used 1.4.2 version of j2me loader☺

**Comment by wb9688** [comment]
I can confirm that that version 3.07.2 indeed works.

**Comment by woesss** [comment]
In the non-working version of the game there is an error. To fix, you need to add a line
`SNAKE_SPEED: null`
in the jar manifest or in the `../J2ME-Loader/converted/Snake III / convert.dex.conf` file of the installed game.  

P.S. Instead of `null` there can be some integer - the speed of the snake will depend on it
