### ISSUE TITLE
 Can Gameloft Classics improve the emulator?

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#655]
Could you improve the emulator with some code from the Gameloft Classics application?

**Comment by stranno** [comment]
Is that even emulation? I have checked the filesystem (data/data/com.gameloft.android.ANMP.GloftGLCL) and I cant see any reference to Java files.

Games have quite some changes over the original Java games, for example all of them are multi-language, when the original games rarely had any language selector, and has A/B button prompts, instead of 5/0.

They could also be Windows Mobile or BREW ports.

**Comment by nikita36078** [comment]
This app is specifically made to emulate a few Gameloft games, nothing insteresting is there. It's more like a port than an emulator.

**Comment by stranno** [comment]
> @stranno They compiled the games into the Android bytecode, that's why you don't see any files - these games are part of the apk.
Then it would be great to dump those versions.

**Comment by stranno** [comment]
It is definitely an emulator, yeah. Here's the compatibility list:

support

jsr 030 - cldc 1.0
jsr 037 - midp 1.0
jsr 075 - file connection 1.0 (pda)
jsr 082 - bluetooth
jsr 118 - midp 2.0
jsr 120 - wma 1.1
jsr 135 - mobile media api
jsr 139 - cldc 1.1
jsr 184 - m3g
jsr 205 - wma 2.0
jsr 234 - amms

sprint api
sprint pcs licence mrc 
nokia UI
samsung api
vodafone vscl 1.1.0
vodafone vscl 2.0
jscl 1.2.2
doja up to doja 5.1

That DOJA tho! It could be the first DOJA emulator ever!

I have checked the APK this time (not the filesystem) and games are just regular Jar files extracted in folders, but they lack the class and manifest files! I have tried to swap games but once i got a nice restart and other time i got a black screen, swaping exactly the same game (of course English only) with an ... scene one (lets say).

Is there any way to swap games? Classes must be in other folder or hardcoded or something.

Of course it is not an alternative for J2ME-Loader, since all games included are just crappy Nokia versions, but that DOJA line makes me dream :-D

**Comment by nikita36078** [comment]
You're getting the black screen because these games are embedded in the emulator. It gave developers the ability to obfuscate both game and emulator code, so, for example, instead of `javax.microedition.lcdui.Image.createImage()` game calls `a.a.b.dl.d()`. Or developer can create a new functions, remove an old ones, since he has 100% control over the game and the "emulator". That's why I said Gameloft Classic look more like port. When you put the java game there, it wasn't able to find original functions (maybe they're renamed, maybe they're removed) and crashed. So you can dump these games, but you can't play them without "unporting" them and it's not worth the time.
I'll look more closer at that half-emulator gibberish, but I don't think they really implemented all these APIs, it just makes zero sense - their games use only the basic APIs - MIDP, CLDC, MMA, Nokia UI and sometimes Bluetooth.

**Comment by stranno** [comment]
> I'll look more closer at that half-emulator gibberish, but I don't think they really implemented all these APIs, it just makes zero sense - their games use only the basic APIs - MIDP, CLDC, MMA, Nokia UI and sometimes Bluetooth.
Gameloft developed games for quite a lot of enviroments, like BREW, Windows Mobile, Symbian, Java ME ... I dont think they worked for DoCoMo but who knows, its a quite obscure market.

Thanks for the explanation, it is clear now.

**Comment by nikita36078** [comment]
I checked the application code - there are no signs of the Doja, Sprint or Vodafone API, only the most basic ones are (partially) implemented.
