### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ezioauditore009** [nikita36078/J2ME-Loader#783]
**Emulator version:**
Latest

**Game version:**
None 

**Game resolution:**
None
None
**Device:**
Galaxy m51

**Android version:**10

**Description of the issue:**
Can u add an option to use another virtual GamePad with ur emulator because the inbuilt controls aren't good neither touch screen if m we could use a virtual GamePad like this one https://play.google.com/store/apps/details?id=com.fishstix.gameboard this GamePad is Very good and most of emulator support it so u should also make support of it

**Comment by xiexin52k** [comment]
![Screenshot](https://user-images.githubusercontent.com/19523795/118099220-8a1f2600-b407-11eb-85df-f987f3572afa.jpg)

u can edit layout like this!! enjoy!

**Comment by MRFRYE009** [comment]
not it's not good add an option so i can use my physical keyboard

**Comment by DavidAriyan** [comment]
> not it's not good add an option so i can use my physical keyboard

NO YOU DON'T NEED THAT EXTERNAL KEYBOARD APP THAT MEANT FOR DOSBOX.
that app is never updated in a long time and have so many compability issues.
j2me loader touchscreen control is already very good and customized. The developer just need to add features missing from the JL-Mod version like mascot 3d and compressed jar.
Please developer just ignore that request above and update j2me loader with more good looking ui and new app icon. Since the new app icon is just meh think.

**Comment by Retroism** [comment]
I use my wee 2t with J2me loader, it already supports physical controller, why do need a keyboard to play java games?
